name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy app via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.218.137.28 << 'EOF'
            cd ~/ceg3120-cicd-BargainBinBastard
            git pull origin main
            docker compose down
            docker compose up -d
          EOF
